/**:
  ros__parameters:
    # ---- 原 launch 里的顶层参数 ----
    use_imu_as_input: false        # true: 用 IMU 作为 Point-LIO 的输入
    prop_at_freq_of_imu: true
    check_satu: true
    init_map_size: 10
    point_filter_num: 4
    space_down_sample: true
    filter_size_surf: 0.5
    filter_size_map: 0.5
    ivox_nearby_type: 6
    runtime_pos_log_enable: false

    common:
      lid_topic: "/velodyne_points"
      imu_topic: "/imu/data"
      con_frame: false             # true: 合并多帧
      con_frame_num: 1
      cut_frame: false             # true: 把一帧切成多个子帧
      cut_frame_time_interval: 0.1
      time_diff_lidar_to_imu: 0.0

    preprocess:
      lidar_type: 2                # 2 Velodyne
      scan_line: 32
      timestamp_unit: 2            # 0-second, 1-ms, 2-us, 3-ns
      blind: 2.0

    mapping:
      imu_en: true
      extrinsic_est_en: false      # 剧烈运动时设为 false
      imu_time_inte: 0.01
      lidar_time_inte: 0.1
      satu_acc: 30.0
      satu_gyro: 35.0
      acc_norm: 9.81
      lidar_meas_cov: 0.01
      acc_cov_output: 500.0
      gyr_cov_output: 1000.0
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      imu_meas_acc_cov: 0.1
      imu_meas_omg_cov: 0.1
      gyr_cov_input: 0.01
      acc_cov_input: 0.1
      plane_thr: 0.1
      match_s: 81.0
      ivox_grid_resolution: 2.0
      gravity: [0.0, 0.0, -9.810]
      gravity_init: [0.0, 0.0, -9.810]
      extrinsic_T: [0.0, 0.0, 0.28]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

    odometry:
      publish_odometry_without_downsample: false

    publish:
      path_en: true
      scan_publish_en: true
      scan_bodyframe_pub_en: false

    pcd_save:
      pcd_save_en: false
      interval: -1
